# Generated by Django 5.0.7 on 2024-07-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicompass_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('score', models.FloatField()),
                ('rank', models.PositiveIntegerField()),
            ],
        ),
    ]
