# Generated by Django 5.0.7 on 2024-07-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicompass_app', '0002_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='THE_University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('scores_overall', models.CharField(max_length=10)),
                ('nid', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('subjects_offered', models.TextField()),
            ],
        ),
    ]
