# Generated by Django 5.0.7 on 2024-08-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicompass_app', '0004_qs_university_delete_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qs_university',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
