# Generated by Django 5.0.7 on 2024-08-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicompass_app', '0005_alter_qs_university_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qs_university',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
