# Generated by Django 5.1 on 2024-08-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicompass_app', '0008_qs_university_rank_agriculture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qs_university',
            name='nid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
