# Generated by Django 5.1 on 2024-08-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicompass_app', '0009_qs_university_nid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qs_university',
            old_name='rank',
            new_name='qs_rank',
        ),
        migrations.RenameField(
            model_name='the_university',
            old_name='rank',
            new_name='the_rank',
        ),
    ]
