# Generated by Django 5.1 on 2024-08-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicompass_app', '0010_rename_rank_qs_university_qs_rank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qs_university',
            old_name='qs_rank',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='the_university',
            old_name='scores_overall',
            new_name='overall_score',
        ),
        migrations.RenameField(
            model_name='the_university',
            old_name='the_rank',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='the_university',
            old_name='name',
            new_name='title',
        ),
    ]
