# Generated by Django 5.1 on 2024-09-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicompass_app', '0012_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='qs_university',
            name='link_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='the_university',
            name='link_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
