# Generated by Django 5.1 on 2024-09-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicompass_app', '0013_qs_university_link_id_the_university_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qs_university',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qs_university',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='the_university',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='the_university',
            name='overall_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='the_university',
            name='subjects_offered',
            field=models.TextField(blank=True, null=True),
        ),
    ]
