# Generated by Django 5.1 on 2024-09-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicompass_app', '0015_qs_university_img_qs_university_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qs_university',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='the_university',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
