# Generated by Django 5.1.1 on 2024-09-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicompass_app', '0017_uniuni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniuni',
            name='the_nid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
