# Generated by Django 5.1.1 on 2024-09-28 14:02

from django.db import migrations

def populate_uniuni_from_qs_and_the(apps, schema_editor):
    UniUni = apps.get_model('unicompass_app', 'UniUni')
    QS_University = apps.get_model('unicompass_app', 'QS_University')
    THE_University = apps.get_model('unicompass_app', 'THE_University')


    # Create UniUni entries from QS_University
    for qs in QS_University.objects.all():
        UniUni.objects.create(
            qs_title=qs.title,
            qs_overall_score=qs.overall_score,
            qs_rank=qs.rank,
            qs_nid=qs.nid,
            qs_city=qs.city,
            qs_country=qs.country,
            qs_rank_arts_humanities=qs.rank_arts_humanities,
            qs_rank_arts=qs.rank_arts,
            qs_rank_linguistics=qs.rank_linguistics,
            qs_rank_music=qs.rank_music,
            qs_rank_theology=qs.rank_theology,
            qs_rank_archaeology=qs.rank_archaeology,
            qs_rank_architecture=qs.rank_architecture,
            qs_rank_art_design=qs.rank_art_design,
            qs_rank_classics=qs.rank_classics,
            qs_rank_english=qs.rank_english,
            qs_rank_history=qs.rank_history,
            qs_rank_art_history=qs.rank_art_history,
            qs_rank_modern_languages=qs.rank_modern_languages,
            qs_rank_performing_arts=qs.rank_performing_arts,
            qs_rank_philosophy=qs.rank_philosophy,
            qs_rank_eng_tech=qs.rank_eng_tech,
            qs_rank_chem_eng=qs.rank_chem_eng,
            qs_rank_civil_eng=qs.rank_civil_eng,
            qs_rank_comp_sci=qs.rank_comp_sci,
            qs_rank_data_sci=qs.rank_data_sci,
            qs_rank_elec_eng=qs.rank_elec_eng,
            qs_rank_pet_eng=qs.rank_pet_eng,
            qs_rank_mech_eng=qs.rank_mech_eng,
            qs_rank_mining_eng=qs.rank_mining_eng,
            qs_rank_nat_sci=qs.rank_nat_sci,
            qs_rank_chemistry=qs.rank_chemistry,
            qs_rank_earth_marine_sci=qs.rank_earth_marine_sci,
            qs_rank_env_sci=qs.rank_env_sci,
            qs_rank_geography=qs.rank_geography,
            qs_rank_geology=qs.rank_geology,
            qs_rank_geophysics=qs.rank_geophysics,
            qs_rank_materials_sci=qs.rank_materials_sci,
            qs_rank_math=qs.rank_math,
            qs_rank_physics_astronomy=qs.rank_physics_astronomy,
            qs_rank_life_sci=qs.rank_life_sci,
            qs_rank_agriculture=qs.rank_agriculture,
            qs_rank_anatomy=qs.rank_anatomy,
            qs_rank_bio_sci=qs.rank_bio_sci,
            qs_rank_dentistry=qs.rank_dentistry,
            qs_rank_medicine=qs.rank_medicine,
            qs_rank_pharmacy=qs.rank_pharmacy,
            qs_rank_nursing=qs.rank_nursing,
            qs_rank_psychology=qs.rank_psychology,
            qs_rank_vet_sci=qs.rank_vet_sci,
            qs_score_nid=qs.score_nid,
        )

    # Create UniUni entries from THE_University
    for the in THE_University.objects.all():
        UniUni.objects.update_or_create(
            the_title=the.title,
            the_overall_score=the.overall_score,
            the_rank=the.rank,
            the_location=the.location,
            defaults={
                'description': the.description,
                'link': the.link,
                'img': the.img,
                'longitude': the.longitude,
                'latitude': the.latitude,
                'the_rank_arts': the.rank_arts,
                'the_rank_eng': the.rank_eng,
                'the_rank_bus': the.rank_bus,
                'the_rank_law': the.rank_law,
                'the_rank_clin': the.rank_clin,
                'the_rank_life': the.rank_life,
                'the_rank_comp': the.rank_comp,
                'the_rank_phys': the.rank_phys,
                'the_rank_edu': the.rank_edu,
                'the_rank_psych': the.rank_psych,
                'the_subjects_offered': the.subjects_offered,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('unicompass_app', '0018_alter_uniuni_the_nid'),
    ]

    operations = [
        migrations.RunPython(populate_uniuni_from_qs_and_the),
    ]
