# Generated by Django 5.1.1 on 2024-09-28 18:05

from django.db import migrations

def populate_uniuni_from_kz(apps, schema_editor):
    UniUni = apps.get_model('unicompass_app', 'UniUni')
    KZ_University = apps.get_model('unicompass_app', 'University')
    
    # Create UniUni entries from QS_University
    for kz in KZ_University.objects.all():
        UniUni.objects.create(
            kz_title=kz.title,
        )
class Migration(migrations.Migration):

    dependencies = [
        ('unicompass_app', '0020_uniuni_kz_title'),
    ]

    operations = [
        migrations.RunPython(populate_uniuni_from_kz),
    ]
