# Generated by Django 5.1.1 on 2024-09-30 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicompass_app', '0021_populate_uniuni_from_kz'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('minimum_score', models.IntegerField()),
                ('available_grants', models.IntegerField()),
                ('academic_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicompass_app.academicprogram')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='unicompass_app.uniuni')),
            ],
            options={
                'unique_together': {('university', 'academic_program', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='QS_University',
        ),
        migrations.DeleteModel(
            name='THE_University',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
